# GENERAL APPLICATION CONFIG SETTINGS
logging:
  level:
    root: info
spring:
  main:
    banner-mode: off

  # DATABASE CONFIG
  datasource:
    url: jdbc:mysql://localhost:3306/ads
    username: root
    password: root

  # JPA/Hibernate Properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
